### ISSUE TITLE
Get email box set up

### ISSUE THREAD

**Issue by mariapraetzellis** [CDLUC3/FAIRIsland#1]
We'll need a dedicated email box to manage communications w/in the DMPTool and for a project newsletter. I'm working with Marisa to get this set up.

**Comment by mariapraetzellis** [comment]
Update from Marisa: " I have a ticket in with UCOP IT to create the mailbox and have coordinated with Martin to update the DNS record on our end.  I’ve asked for a time estimate and will let you know what they say."

**Comment by mariapraetzellis** [comment]
We've decided to go with Google Suite to manage the FAIR Island email box. @erinmr will set this up via Metadata Game Changers.

**Comment by erinmr** [comment]
@mariapraetzellis Does Google suite exist for FAIRIsland.org?
