### ISSUE TITLE
Fix DOIs in MERRITT for Moorea Biocode

### ISSUE THREAD

**Issue by erinmr** [CDLUC3/FAIRIsland#11]
characters that Merritt is expecting.

 

For example, doi.org/10.7286/V1154F0D targets https://merritt.cdlib.org/m/ark:/13030/m5zs409j/1

 

However, the target URL should look like this instead: https://merritt.cdlib.org/m/ark%253A%252F13030%252Fm5zs409j

Note the colon character has been replaced with “%253A” and the following forward slashes with “%252F”.

 

Do you have access to the Biocode Commons account in EZID to revise the target URLs so they make use of double-escaped characters? If not, Maria Gould mentioned that John Deck should have access (perhaps Neil does as well).

 

On a similar note, EZID can also be used to register a new DOI for ark:/13030/m5478zfg. Once it’s registered, I’d be happy to help with adding it as a local identifier to the object in Merritt.

 

One other question: Do you want the target URLs to always resolve to the latest version of the object in Merritt? If so, please omit the trailing forward slash and number at the end of the URL. e.g. “/1”  The number refers to a specific version, while omitting it just pulls up the latest version.

**Comment by mariapraetzellis** [comment]
Citations for the missing Merritt items:

V1154F0D
`Moorea Biocode Project (2014). "Moorea Biocode Field Information Management System (FIMS)" 
`

V1MW2F22
`Moorea Biocode Project (2014). Moorea Biocode Laboratory Information Management System (LIMS)"`

V1H41PBN
`Moorea Biocode Project (2014).  "Moorea Biocode Laboratory Information Management System Trace and Gel Images" 
`

**Comment by briri** [comment]
Ok. I have manually updated them in the DB and also changed the book chapter from a dataset to an article

**Comment by erinmr** [comment]
thanks for fixing this @briri!
