### ISSUE TITLE
Create a new dmp page is confusing with funder and research org. TS users don't want to pick TS for funder or research org

### ISSUE THREAD

**Issue by erinmr** [CDLUC3/FAIRIsland#14]

**Comment by mariapraetzellis** [comment]
We're creating a new workflow for FAIR Island users that do not come from RAMS. This work is being tracked here: https://github.com/CDLUC3/dmptool/issues/299

Additionally, we can send the TS template directly to a user (skipping the create plan page) by using [this link ](https://dmptool.org/plans?plan%5Bfunder%5D%5Bid%5D=%7B+%22id%22%3A+1830%2C+%22name%22%3A+%22Tetiaroa+Society%22+%7D&plan%5Borg%5D%5Bid%5D=%7B+%22id%22%3A+15%2C+%22name%22%3A+%22University+of+California%2C+Office+of+the+President+%28UCOP%29%22+%7D&plan%5Btemplate_id%5D=1363)

**Comment by mariapraetzellis** [comment]
We deployed a new feature that allows DMPTool administrators to send a link to enable users to create a plan directly and skip the Creat Plan Wizard that was confusing to users.
