### ISSUE TITLE
Post grant announcement 

### ISSUE THREAD

**Issue by mariapraetzellis** [CDLUC3/FAIRIsland#2]
Post NSF EAGER grant [announcement](https://docs.google.com/document/d/1CyJGaui8ODtebHI8EBFufJuVEcjnutPS8Z4tng4erUc/edit). Should go to:
- DMPTool blog
- FAIR Island site
- UC3 blog
- ?? others ??

**Comment by erinmr** [comment]
thanks for doing this, @mariapraetzellis 🥳
