### ISSUE TITLE
Create PIDGraph for Moorea Biocode DMP

### ISSUE THREAD

**Issue by erinmr** [CDLUC3/FAIRIsland#6]
- [x] Create Initial PIDGraph with Datacite DMP Notebook
- [x] Add DOI products to DMP 
- [x] Create an updated PIDGraph showing products

**Comment by erinmr** [comment]
From Kristian:  If that's the case the graph can be generated directly from maDMPs notebooks website (https://github.com/datacite/pidgraph-notebooks-python/tree/master/dmp). I ran the notebook from the website with your DMP DOI but it is not connected to anything (see attached picture). I think this is where you need connections to outputs.  But it is not about sending the DOIs to us, but to add them in the metadata of the DMP. The DMP Documentation would be a good place for you to check how to do that. 

![image](https://user-images.githubusercontent.com/2915555/129081069-fe9660b8-20d7-4f6a-9ad1-50d7fe8b5b69.png)

**Comment by erinmr** [comment]
From Kristian: 

As you said we have to go backwards. In normal operation we would expect that the related publications and datasets would have a link to the DMP-ID (10.48321/D1F88S) in their metadata. Currently, according to our system there is not a single DOI related to the DMP-ID 10.48321/D1F88S. 

W/r/t your question, if you were to had a list of all the DOIs of the related publications and datasets , you could take that list and add it in DMP-ID (10.48321/D1F88S) metadata in dmphub (https://dmphub.cdlib.org/dmps/doi:10.48321/D1F88S) following the documentation. https://support.datacite.org/docs/link-dmp-ids-to-other-resources

**Comment by mariapraetzellis** [comment]
Gif of this DOI is attached. 
![MooreaBiocodeDMP-ID](https://user-images.githubusercontent.com/27511575/130648722-fdd6e628-687e-4bad-95c3-fc65cfc5a3eb.gif)

Brian has fixed existing issues with the Merritt dataset citations and the misidentified book chapter.
